/* Palette generator for the CorpusTrace site.
 *
 *   node scripts/generate-palette.mjs            # list configurations
 *   node scripts/generate-palette.mjs <id>       # write that configuration into styles.css
 *   node scripts/generate-palette.mjs <id> --verify   # print every enforced ratio, write nothing
 *   node scripts/generate-palette.mjs <id> --stdout   # print the CSS, write nothing
 *
 * WHY THIS EXISTS
 * ---------------
 * The site's contrast failures were never a hue problem. One token, --text-faint, was
 * placed on three different surfaces and failed at three different ratios (3.03, 3.22,
 * 3.33) — because nothing decided what job that token had. Swapping in a prettier palette
 * and assigning captions to an equally light step reproduces every failure in new hues.
 *
 * So colour is no longer chosen; it is DERIVED. Each scale is twelve steps with a fixed
 * job, borrowed from Radix Colors' step semantics:
 *
 *    1-2   app and subtle backgrounds
 *    3-5   component backgrounds: normal, hover, active
 *    6-8   borders and separators: subtle, normal, strong
 *    9-10  solid fills: normal, hover
 *    11    low-contrast accessible text
 *    12    high-contrast text
 *
 * The VALUES are generated here rather than taken from Radix, for one concrete reason:
 * Radix's scales are tuned for APCA, which models perception better than WCAG 2.x but
 * disagrees with it at the edges — particularly light text on mid-tone backgrounds. Our
 * gate is stated as WCAG AA, so the WCAG number is the one that has to hold, and the only
 * way to hold it is to compute it. Every step below is walked along its lightness axis
 * until it measurably passes, against EVERY surface it is allowed to sit on. That last
 * clause is the whole fix: the old grey passed on one surface and was never checked
 * against the other two.
 *
 * A configuration therefore contains no hex. It contains hue angles and chroma targets —
 * the part that is a design decision — and nothing that could be wrong about arithmetic.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const CSS = resolve(HERE, '../assets/css/styles.css');
const START = '/* PALETTE-BLOCKS:START — generated by scripts/generate-palette.mjs. Do not hand-edit. */';
const END = '/* PALETTE-BLOCKS:END */';

/* ------------------------------------------------------------------ colour maths */

const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
const linearToSrgb = (c) => (c <= 0.0031308 ? c * 12.92 : 1.055 * Math.pow(c, 1 / 2.4) - 0.055);

/* OKLCH -> linear sRGB -> sRGB. Björn Ottosson's matrices. */
function oklchToRgb(L, C, h) {
  const hr = (h * Math.PI) / 180;
  const a = C * Math.cos(hr);
  const b = C * Math.sin(hr);

  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.0894841775 * a - 1.291485548 * b;
  const l = l_ * l_ * l_, m = m_ * m_ * m_, s = s_ * s_ * s_;

  return [
    linearToSrgb(4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s),
    linearToSrgb(-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s),
    linearToSrgb(-0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s),
  ];
}

const IN_GAMUT = (rgb) => rgb.every((c) => c >= -0.0002 && c <= 1.0002);

/* Reduce chroma until the colour is representable in sRGB. Reducing chroma rather than
   clipping channels keeps the hue and the lightness — clipping shifts both, which is how
   two steps of the same scale end up looking like different hues. */
function gamutFit(L, C, h) {
  if (IN_GAMUT(oklchToRgb(L, C, h))) return C;
  let lo = 0, hi = C;
  for (let i = 0; i < 24; i++) {
    const mid = (lo + hi) / 2;
    if (IN_GAMUT(oklchToRgb(L, mid, h))) lo = mid; else hi = mid;
  }
  return lo;
}

function toHex(L, C, h) {
  const C2 = gamutFit(L, C, h);
  const rgb = oklchToRgb(L, C2, h).map((c) => Math.max(0, Math.min(255, Math.round(c * 255))));
  return '#' + rgb.map((v) => v.toString(16).padStart(2, '0')).join('');
}

const hexToRgb = (hex) => [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16));
const relLum = (hex) => {
  const [r, g, b] = hexToRgb(hex).map((v) => srgbToLinear(v / 255));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrast = (a, b) => {
  const x = relLum(a), y = relLum(b);
  return (Math.max(x, y) + 0.05) / (Math.min(x, y) + 0.05);
};

/* ---------------------------------------------------- colour-vision simulation */

/* Viénot, Brettel & Mollon (1999) dichromat simulation. The matrices operate on LINEAR
 * sRGB, which is why the conversion happens either side of them.
 *
 * This exists because six independent critiques of three different palettes all reached the
 * same conclusion: the seven syntax colours were separated by HUE ALONE and all sat on one
 * lightness step, so a red-green dichromat saw three or four colours rather than seven. Hue
 * separation cannot be fixed by rotating hues — the wheel folds onto a line — so lightness
 * has to carry a share of the difference. An obligation that is not measured is a wish, so
 * the simulation is here rather than in a comment. */
const CVD = {
  deuteranopia: [[0.625, 0.375, 0.0], [0.700, 0.300, 0.0], [0.0, 0.300, 0.700]],
  protanopia: [[0.1667, 0.8333, 0.0], [0.1667, 0.8333, 0.0], [0.0, 0.1250, 0.8750]],
};

function simulate(hex, kind) {
  const m = CVD[kind];
  const lin = hexToRgb(hex).map((v) => srgbToLinear(v / 255));
  const out = m.map((row) => row[0] * lin[0] + row[1] * lin[1] + row[2] * lin[2]);
  const rgb = out.map((c) => Math.max(0, Math.min(255, Math.round(linearToSrgb(Math.max(0, Math.min(1, c))) * 255))));
  return '#' + rgb.map((v) => v.toString(16).padStart(2, '0')).join('');
}

/* ------------------------------------------------------------------ scale building */

/* Seed lightness per step. These are starting points only; anything with a contrast
   obligation is moved until it meets it, so a seed being slightly off costs nothing. */
const L_LIGHT = [0.993, 0.976, 0.952, 0.930, 0.906, 0.874, 0.826, 0.740, 0.586, 0.548, 0.512, 0.242];
const L_DARK  = [0.178, 0.212, 0.256, 0.292, 0.324, 0.372, 0.436, 0.524, 0.640, 0.686, 0.782, 0.948];

/* Chroma multiplier per step: quiet at the background end, peaking at the solid fill,
   easing off again for text so a caption reads as text rather than as a coloured object. */
const C_CURVE = [0.055, 0.095, 0.175, 0.255, 0.330, 0.415, 0.510, 0.660, 1.000, 0.975, 0.720, 0.360];

/* The obligations. Indices are 1-based step numbers to match the vocabulary above.
 *
 * step12 is 10.0 and not 13.0 for a measured reason: in dark mode the most contrasting
 * surface text is allowed to sit on is gray.4, and pure white against it tops out at
 * 14.17:1 — so a 13:1 obligation is satisfiable only by abandoning the scale's tint
 * entirely and using near-#ffffff. 10:1 is comfortably past AAA (7:1), holds on every
 * surface rather than only on the page, and leaves the neutral its hue. */
const NEED = {
  step8: 3.0,    // strong border and graphic line: carries meaning (SC 1.4.11)
  step9: 3.0,    // a solid fill must be distinguishable from the page it sits on
  step11: 4.5,   // low-contrast accessible text (SC 1.4.3)
  step12: 10.0,  // high-contrast text, on every surface
  onSolid: 4.5,  // text placed on step 9

  /* OKLab distance required between two colours that carry different meaning, measured
     AFTER dichromat simulation. Syntax tokens get the lower bar because seven of them have
     to fit on one surface and the alternative is fewer token types; brand hues get the
     higher bar because there are only three and they are the page's structure. */
  cvdSyntax: 0.055,
  cvdBrand: 0.075,
};

/* THE SURFACE SET. Steps 1-4 are the app background, the subtle background and the two
 * component backgrounds — every surface a caption can land on. Text obligations are
 * checked against ALL of them, which is the entire correction: the token this replaces
 * passed on one surface, was never checked against the other two, and failed on both. */
const TEXT_ON = [1, 2, 3, 4];

function buildScale({ hue, chroma, mode, beds, extraBeds, bias }) {
  const Ls = (mode === 'dark' ? L_DARK : L_LIGHT).slice();
  /* A per-hue lightness bias applied to the SOLID and TEXT steps only, so that three brand
     hues differ in lightness as well as in angle. Same reasoning as the syntax tiers: under
     red-green simulation two of the three hues routinely fold together, and lightness is the
     channel that survives. Backgrounds and borders keep their seeds, because shifting those
     would change the surface set every text obligation is measured against. */
  if (bias) [8, 9, 10, 11].forEach((i) => { Ls[i] = Math.max(0.05, Math.min(0.96, Ls[i] + bias)); });
  const dir = mode === 'dark' ? +1 : -1;   // which way is "more contrast against the page"
  const hexAt = (i) => toHex(Ls[i], C_CURVE[i] * chroma, hue);

  /* Steps 1-4 carry no obligation, so they never move and can be resolved up front.
     For a neutral scale they ARE the surface set; for a hue scale the neutral surfaces
     are passed in and this scale's own tints are added — a teal chip label sits on a teal
     tint, and checking only the page background is how that one reached just 3.31:1. */
  const ownSurfaces = TEXT_ON.map((s) => hexAt(s - 1));
  const surfaceBeds = (beds && beds.length ? beds.concat(hexAt(1), hexAt(2)) : ownSurfaces)
    .concat(extraBeds || []);
  const pageBeds = (beds && beds.length ? beds : ownSurfaces).slice(0, 2);

  const walk = (step, target, list) => {
    const i = step - 1;
    for (let n = 0; n < 500; n++) {
      const worst = Math.min(...list.map((bed) => contrast(hexAt(i), bed)));
      if (worst >= target) return true;
      Ls[i] += dir * 0.002;
      if (Ls[i] <= 0.015 || Ls[i] >= 0.997) return false;   // clamped: --verify reports it
    }
    return false;
  };

  walk(8, NEED.step8, surfaceBeds);
  walk(11, NEED.step11, surfaceBeds);
  walk(12, NEED.step12, surfaceBeds);
  walk(9, NEED.step9, pageBeds);

  /* Text on the solid fill. The candidates are the two ends of this scale; if neither
     clears 4.5:1 the SOLID moves, not the obligation. Walking step 9 further from the page
     raises its contrast with whichever end is winning, in both themes — so this converges
     rather than fighting the step-9 walk above. */
  const bestOnSolid = () => Math.max(contrast(hexAt(0), hexAt(8)), contrast(hexAt(11), hexAt(8)));
  for (let n = 0; n < 500 && bestOnSolid() < NEED.onSolid; n++) {
    Ls[8] += dir * 0.002;
    if (Ls[8] <= 0.015 || Ls[8] >= 0.997) break;
  }

  // Step 10 is the hover of step 9: one nudge further from the page, never less.
  Ls[9] = Ls[8] + dir * 0.038;

  const steps = Ls.map((_, i) => hexAt(i));
  const onSolid = contrast(steps[0], steps[8]) >= contrast(steps[11], steps[8]) ? steps[0] : steps[11];

  return { steps, onSolid, surfaces: ownSurfaces, L: Ls.slice() };
}

/* A single colour pinned to a surface — used for the code-block island and for status
   colours, which are not full scales because nothing needs their hover state. */
function pinned({ hue, chroma, bg, target, mode, seedL }) {
  const beds = Array.isArray(bg) ? bg : [bg];
  let L = seedL !== undefined ? seedL : (mode === 'dark' ? 0.70 : 0.55);
  // Walk away from the LIGHTEST bed in a light theme, the darkest in a dark one, so the
  // result clears every bed rather than only the one that happened to be passed first.
  const dir = relLum(beds.reduce((a, b) => (relLum(a) > relLum(b) ? a : b))) > 0.5 ? -1 : +1;
  for (let n = 0; n < 500; n++) {
    const hex = toHex(L, chroma, hue);
    if (Math.min(...beds.map((b) => contrast(hex, b))) >= target) return hex;
    L += dir * 0.002;
    if (L <= 0.015 || L >= 0.997) break;
  }
  return toHex(L, chroma, hue);
}

/* ------------------------------------------------------------------ configurations */

/* Status hues are held CONSTANT across every configuration on purpose: a warning that is
   amber in one candidate and violet in another is a different claim about the page, not a
   different palette. Only the brand hues vary. */
const STATUS = { warn: { hue: 70, chroma: 0.15 }, dang: { hue: 22, chroma: 0.18 } };

/* THE POINTER.
 *
 * The lens cursor replaces the system pointer, so its visibility is not a matter of
 * taste — it is the only thing telling the reader where they are. It used to be
 * painted in `--primary` at 72% alpha over a 1.5px border with a 55%-alpha halo, and
 * measured on screen that came to 25 of 1,183 cursor pixels clearing 3:1 on a card in
 * the light theme, and 0 of 117 over the code island in the dark theme. A pointer
 * nobody can find is the same defect as no pointer at all, which is the one thing the
 * note above `.has-lens-cursor` in styles.css exists to prevent.
 *
 * THE INK IS A STATED CHOICE, NOT A DERIVED VALUE. This is the only literal hex in
 * this file, and it is here because the colour was specified rather than computed.
 * It is still VERIFIED by the obligations below — being chosen does not exempt it.
 *
 * IT IS TWO-TONE, AND WITH THIS INK THE HALO IS DOING MOST OF THE WORK. #45dfca is a
 * light mint: 11:1 against the dark code island and 8.6:1 against the dark theme's
 * surfaces, but only 1.3–1.6:1 against a light page — on its own it would be close to
 * invisible in the light theme, which is the very complaint that started this. So the
 * halo is the DARK end of the neutral scale in both modes, full opacity, sandwiching
 * the ink line on both sides. On a light page the dark rim carries the shape (13–16:1)
 * and the mint reads as its colour; on a dark surface the mint carries it and the rim
 * gives it an edge. That is the same arrangement as a light-coloured OS pointer, which
 * is a pale shape with a black outline for exactly this reason.
 *
 * Which is why the obligation below is stated on the PAIR rather than on the ink: for
 * every surface, at least one of the two tones must clear 4.5:1, and the two must
 * clear 3:1 against each other so the shape reads as a shape. An obligation on the ink
 * alone would reject this colour outright while a correctly-built two-tone mark using
 * it is comfortably visible everywhere.
 *
 * Note the ink coincides with the dark theme's accent solid (hue2 step 9), so in dark
 * mode the pointer shares a colour with accent fills rather than standing apart from
 * the palette. That is a consequence of the choice, not a fault in it. */
const CURSOR_INK = '#45dfca';

const CONFIGS = {};

export function defineConfig(id, cfg) { CONFIGS[id] = { id, ...cfg }; }

/* THE CONTROL. Today's hue angles, correctly role-mapped. It exists so the effect of the
   role map can be separated from the effect of the hues: it takes the site from 19
   gate-relevant contrast failures to 0 while looking almost identical, which is the
   evidence that the failures were never about which colours were chosen. */
defineConfig('baseline-tinted', {
  name: 'Baseline',
  character: 'Today\'s hues, correctly role-mapped — the control, not a candidate.',
  grayHue: 265, grayChroma: 0.009,
  hues: [
    { slot: 'hue1', hue: 272, chromaPeak: 0.185 },
    { slot: 'hue2', hue: 182, chromaPeak: 0.130 },
    { slot: 'hue3', hue: 70, chromaPeak: 0.150, bias: 0.060 },
  ],
  code: { hue: 265, chroma: 0.012, tokens: [
    { token: 'comment', hue: 265 }, { token: 'string', hue: 150 }, { token: 'keyword', hue: 290 },
    { token: 'builtin', hue: 230 }, { token: 'number', hue: 80 }, { token: 'key', hue: 330 },
    { token: 'flag', hue: 20 },
  ] },
  surfaceTemperature: [],
});

/* ---- The three candidates. Hue angles and chroma targets only: no hex, and no claim
   about contrast, because every one of those is computed above. ---- */

defineConfig('sextant', {
  name: 'Sextant',
  character: 'Navy blueprint, brass highlighter, jade instrument panel — three temperatures instead of one blue.',
  grayHue: 242, grayChroma: 0.015,
  hues: [
    { slot: 'hue1', hue: 272, chromaPeak: 0.190 },   // structure and interface
    { slot: 'hue2', hue: 46, chromaPeak: 0.160 },    // evidence — every state meaning FOUND
    // Amber and jade fold toward one another under protanopia (measured 0.071 at step 9,
    // against a 0.075 floor). Biasing jade darker separates them by lightness, which
    // survives the fold — and keeps the three-temperature idea that moving jade to teal,
    // the other available fix, would have destroyed.
    { slot: 'hue3', hue: 158, chromaPeak: 0.130, bias: 0.075 },
  ],
  code: { hue: 242, chroma: 0.012, tokens: [
    { token: 'comment', hue: 242 }, { token: 'string', hue: 158 }, { token: 'keyword', hue: 285 },
    { token: 'builtin', hue: 210 }, { token: 'number', hue: 82 }, { token: 'key', hue: 328 },
    { token: 'flag', hue: 18 },
  ] },
});

defineConfig('filament', {
  name: 'Filament',
  character: 'Warm lamplight on sand-coloured paper, cool instrument colours for the machinery — the lit line is amber, not blue.',
  grayHue: 58, grayChroma: 0.012,
  hues: [
    { slot: 'hue1', hue: 44, chromaPeak: 0.175 },    // evidence and interaction — the lens light
    { slot: 'hue2', hue: 206, chromaPeak: 0.140 },   // architecture and data — the machine
    { slot: 'hue3', hue: 292, chromaPeak: 0.180, bias: 0.060 },   // retrieval strategies
  ],
  code: { hue: 58, chroma: 0.012, tokens: [
    { token: 'comment', hue: 48 }, { token: 'string', hue: 145 }, { token: 'keyword', hue: 282 },
    { token: 'builtin', hue: 206 }, { token: 'number', hue: 62 }, { token: 'key', hue: 330 },
    { token: 'flag', hue: 18 },
  ] },
});

defineConfig('voltage', {
  name: 'Voltage',
  character: 'Electric pink and signal green flaring off a faintly violet page — lit from behind rather than printed.',
  grayHue: 300, grayChroma: 0.019,
  hues: [
    /* 350, not the authored 328. Magenta at 328 and azure at 238 collapse under protanopia
       (measured 0.075 at step 9, 0.072 at step 11 against a 0.075 floor) and the lightness
       search exhausted itself without clearing it. Its own critique measured the repair and
       named the safe band: move hue1 toward 350, never past 358, and never into 5-40 where it
       would collide with the danger status colour. */
    { slot: 'hue1', hue: 350, chromaPeak: 0.240 },   // the lit match
    { slot: 'hue2', hue: 148, chromaPeak: 0.190 },   // the ground it stands on — data, readiness
    // Magenta and azure collapse under protanopia; azure is biased darker for the same
    // reason, rather than rotating magenta into the red band where it would collide with
    // the danger status colour.
    { slot: 'hue3', hue: 238, chromaPeak: 0.170, bias: 0.075 },   // the instrument
  ],
  code: { hue: 300, chroma: 0.012, tokens: [
    { token: 'comment', hue: 300 }, { token: 'string', hue: 148 }, { token: 'keyword', hue: 328 },
    { token: 'builtin', hue: 238 }, { token: 'number', hue: 78 }, { token: 'key', hue: 28 },
    { token: 'flag', hue: 190 },
  ] },
});

/* ------------------------------------------------- solving the brand-hue biases */

/* Same lesson as the syntax tokens, one level up: hand-picking a lightness bias to separate
 * two brand hues under simulation does not work, because you cannot see post-simulation
 * space from authored space. A bias of 0.075 chosen by eye moved Sextant's amber/jade pair
 * from 0.071 to 0.059 — the wrong way.
 *
 * So the bias is searched rather than chosen. For each configuration the grid below is
 * evaluated over BOTH themes and BOTH dichromat conditions, and the combination with the
 * best worst-case separation wins. This is safe to search freely because buildScale applies
 * the bias BEFORE its contrast walks — every candidate is contrast-valid by construction, so
 * the search can only trade aesthetics, never accessibility.
 *
 * hue1 is held at zero: it is the interface hue and its solid is the one colour a returning
 * visitor recognises, so the other two move around it. */
const BIAS_GRID = [0, 0.02, 0.04, 0.06, 0.08, 0.10, 0.12, 0.15, 0.18];
/* hue1 is the interface hue — the solid a returning visitor recognises — so it is allowed to
   move, but only a little, and the tie-break below prefers leaving it alone. */
const BIAS_GRID_1 = [0, 0.03, 0.06];
const _biasCache = new Map();

function solveBiases(cfg) {
  if (_biasCache.has(cfg.id)) return _biasCache.get(cfg.id);

  const perMode = ['light', 'dark'].map((mode) => {
    const Lseed = mode === 'dark' ? L_DARK : L_LIGHT;
    const washBeds = cfg.hues.flatMap((h) => [2, 3].map((st) =>
      toHex(Lseed[st - 1], C_CURVE[st - 1] * h.chromaPeak, h.hue)));
    const gray = buildScale({ hue: cfg.grayHue, chroma: cfg.grayChroma, mode, extraBeds: washBeds });
    return { mode, beds: gray.surfaces, washBeds };
  });

  const scoreFor = (b2, b3, b1) => {
    let worst = Infinity;
    for (const { mode, beds, washBeds } of perMode) {
      const sgn = mode === 'dark' ? 1 : -1;
      const scales = cfg.hues.map((h, i) => buildScale({
        hue: h.hue, chroma: h.chromaPeak, mode, beds, extraBeds: washBeds,
        bias: sgn * (i === 1 ? b2 : i === 2 ? b3 : b1),
      }));
      for (const kind of ['deuteranopia', 'protanopia']) {
        for (const st of [9, 11]) {
          for (let i = 0; i < scales.length; i++) {
            for (let j = i + 1; j < scales.length; j++) {
              const d = deltaE(simulate(scales[i].steps[st - 1], kind), simulate(scales[j].steps[st - 1], kind));
              if (d < worst) worst = d;
            }
          }
        }
      }
    }
    return worst;
  };

  let best = { score: -1, b1: 0, b2: 0, b3: 0 };
  for (const b1 of BIAS_GRID_1) {
    for (const b2 of BIAS_GRID) {
      for (const b3 of BIAS_GRID) {
        const score = scoreFor(b2, b3, b1);
        // Ties go to the smaller total bias: a scheme should differ by hue where it can, and
        // spend lightness only where hue has stopped working. hue1 is weighted double so it
        // is the last thing the search reaches for.
        const cost = b1 * 2 + b2 + b3;
        const bestCost = best.b1 * 2 + best.b2 + best.b3;
        if (score > best.score + 1e-9
          || (Math.abs(score - best.score) < 1e-9 && cost < bestCost)) {
          best = { score, b1, b2, b3 };
        }
      }
    }
  }
  const out = { hue1: best.b1, hue2: best.b2, hue3: best.b3, score: best.score };
  _biasCache.set(cfg.id, out);
  return out;
}

/* ------------------------------------------------------------------ theme assembly */

function buildTheme(cfg, mode) {
  /* SECTION WASHES, resolved before anything else. Steps 2 and 3 of each brand hue are
     used as a soft wash behind whole sections, so the page changes temperature as the
     reader descends — rule 3 of the hue brief: temperature on surfaces, never on type.
     They can be computed up front because steps 1-4 carry no contrast obligation and are
     therefore just their seeds. Computing them FIRST is the point: every text step below
     is then walked against the washes as well as against the neutral surfaces, so a tinted
     section cannot quietly invalidate a ratio that was verified on the untinted one. */
  const Lseed = mode === 'dark' ? L_DARK : L_LIGHT;
  const washes = cfg.hues.map((h) => ({
    slot: h.slot,
    hexes: [2, 3].map((st) => toHex(Lseed[st - 1], C_CURVE[st - 1] * h.chromaPeak, h.hue)),
  }));
  const washBeds = washes.flatMap((w) => w.hexes);

  const gray = buildScale({ hue: cfg.grayHue, chroma: cfg.grayChroma, mode, extraBeds: washBeds });

  /* The four surfaces text is allowed to land on, resolved from the neutral scale. The
     mapping differs by theme for exactly two roles and that is not an inconsistency:
     in light mode a raised card is WHITER than the page, in dark mode it is LIGHTER than
     the page. Both mean "toward the viewer"; only one of them means "toward step 1". */
  const surfaces = mode === 'dark'
    ? { bg: 1, bgSubtle: 2, surface: 3, raised: 4 }
    : { bg: 2, bgSubtle: 3, surface: 1, raised: 1 };

  /* Every surface text can land on, not merely the ones the four semantic names happen to
     point at — steps 4 and 5 are component hover/active states and text sits on those too. */
  const surfaceHexes = gray.surfaces;

  /* A DELIBERATE DEVIATION from Radix's twelve steps, documented rather than hidden.
     Radix gives exactly two accessible text steps: 11 (low contrast) and 12 (high). This
     page's information design needs three — heading, body, caption — and the old design
     got its third by going lighter than 11, which is precisely why it failed at 3.03:1.
     So the third level is generated INWARD instead: held at AAA 7:1, between 11 and 12.
     Going inward can only ever be safe; going outward is the bug this replaces. */
  const textMid = pinned({ hue: cfg.grayHue, chroma: cfg.grayChroma * 0.62, bg: gray.surfaces.concat(washBeds), target: 7.0, mode });

  const hues = cfg.hues.map((h) => ({
    slot: h.slot,
    scale: buildScale({ hue: h.hue, chroma: h.chromaPeak, mode, beds: surfaceHexes, extraBeds: washBeds,
      bias: (mode === 'dark' ? 1 : -1) * (solveBiases(cfg)[h.slot] || 0) }),
    hue: h.hue,
  }));

  /* The code block is a dark island in BOTH themes, so its tokens are pinned to its own
     surface rather than to the page. In light mode that surface is the one place where a
     light-theme accent has to survive on a dark bed — which is how the focus ring came to
     fail there at 2.82:1 while passing everywhere else. */
  const codeBg = toHex(mode === 'dark' ? 0.168 : 0.202, cfg.code.chroma, cfg.code.hue);
  const codeBorder = toHex(mode === 'dark' ? 0.246 : 0.276, cfg.code.chroma, cfg.code.hue);
  const codeText = pinned({ hue: cfg.code.hue, chroma: 0.010, bg: codeBg, target: 13, mode: 'dark' });
  const codeMuted = pinned({ hue: cfg.code.hue, chroma: 0.014, bg: codeBg, target: 4.5, mode: 'dark' });
  const SYNTAX_CHROMA = 0.115;
  const COMMENT_CHROMA = 0.026;

  /* Every token gets its OWN lightness, deliberately spread. This is the fix for the
     collapse described above: two tokens that a dichromat cannot tell apart by hue are
     still told apart by being visibly lighter or darker. The seeds are spread as widely as
     4.5:1 on the code surface allows; anything that falls short is walked up by pinned(),
     so the spread never costs contrast. */
  const SYNTAX_L = {
    key: 0.615, comment: 0.655, number: 0.690, keyword: 0.730,
    string: 0.765, flag: 0.840, builtin: 0.915,
  };
  // Carry their own non-colour channel (italic / bold), so colour is not their only cue.
  const STYLED = new Set(['comment', 'keyword']);
  const codeTokens = cfg.code.tokens.map((t) => {
    const chroma = t.token === 'comment' ? COMMENT_CHROMA : SYNTAX_CHROMA;
    return {
      token: t.token, hue: t.hue, chroma,
      styled: STYLED.has(t.token),
      L: SYNTAX_L[t.token],
      hex: pinned({ hue: t.hue, chroma, bg: codeBg, target: 4.5, mode: 'dark', seedL: SYNTAX_L[t.token] }),
    };
  });

  /* SEPARATE THE TOKENS IN SIMULATED SPACE, not in authored space.
   *
   * Spreading their authored lightness was not enough, and the reason is worth writing down:
   * dichromat simulation CHANGES lightness. Green carries most of the luminance signal, so a
   * green loses lightness when the red-green axis is collapsed, while a purple gains it —
   * which means two tokens deliberately set 0.15 apart can cross over and land on top of one
   * another. Measured: string at L 0.765 and key at L 0.615 came out 0.023 apart after
   * simulation, against a 0.055 floor.
   *
   * So the obligation is solved where it is stated. Each round finds the closest simulated
   * pair across both conditions and pushes them apart along lightness, refusing any move
   * that would drop a token below 4.5:1 on the code surface — a token that separates by
   * going illegible has not been fixed. */
  {
    const styleless = codeTokens.filter((c) => !c.styled);
    const hexOf = (c) => toHex(c.L, c.chroma, c.hue);
    const simLum = (c, kind) => relLum(simulate(hexOf(c), kind));
    const legible = (c, L) => contrast(toHex(L, c.chroma, c.hue), codeBg) >= NEED.step11;

    for (let iter = 0; iter < 600; iter++) {
      let worst = null;
      for (const kind of ['deuteranopia', 'protanopia']) {
        for (let i = 0; i < styleless.length; i++) {
          for (let j = i + 1; j < styleless.length; j++) {
            const d = deltaE(simulate(hexOf(styleless[i]), kind), simulate(hexOf(styleless[j]), kind));
            if (!worst || d < worst.d) worst = { d, a: styleless[i], b: styleless[j], kind };
          }
        }
      }
      if (!worst || worst.d >= NEED.cvdSyntax) break;
      const { a, b, kind } = worst;
      const lo = simLum(a, kind) <= simLum(b, kind) ? a : b;
      const hi = lo === a ? b : a;
      const STEP = 0.004;
      let moved = false;
      if (legible(lo, lo.L - STEP) && lo.L - STEP > 0.30) { lo.L -= STEP; moved = true; }
      if (hi.L + STEP < 0.985) { hi.L += STEP; moved = true; }
      if (!moved) break;   // nowhere left to go: --verify reports the shortfall honestly
    }
    codeTokens.forEach((c) => { c.hex = toHex(c.L, c.chroma, c.hue); });
  }

  const status = {
    warn: pinned({ ...STATUS.warn, bg: surfaceHexes[0], target: 4.5, mode }),
    dang: pinned({ ...STATUS.dang, bg: surfaceHexes[0], target: 4.5, mode }),
  };
  const warnScale = buildScale({ hue: STATUS.warn.hue, chroma: STATUS.warn.chroma, mode, beds: surfaceHexes });
  const dangScale = buildScale({ hue: STATUS.dang.hue, chroma: STATUS.dang.chroma, mode, beds: surfaceHexes });

  /* The focus ring must clear 3:1 against the page AND against the code island. One value
     cannot do both in light mode, so the island carries a scoped override — a local token,
     not a second rule to remember. */
  const h1 = hues[0].scale;
  const ringPage = h1.steps[8];
  const ringOnCode = pinned({ hue: hues[0].hue, chroma: 0.16, bg: codeBg, target: 3.0, mode: 'dark' });

  /* The pointer — see CURSOR_INK above. The halo is the DARK end of the neutral scale
     in whichever mode this is (step 12 in light, step 1 in dark), picked by luminance
     rather than by index so it cannot silently invert if the scale's direction ever
     changes. It has to be the dark end in BOTH modes because the ink is light in both. */
  const cursorHalo = [gray.steps[0], gray.steps[11]]
    .reduce((a, b) => (relLum(a) < relLum(b) ? a : b));
  const cursorInk = CURSOR_INK;

  return { gray, hues, textMid, washes, washBeds, surfaces, surfaceHexes, codeBg, codeBorder, codeText, codeMuted, codeTokens, status, warnScale, dangScale, ringPage, ringOnCode, cursorInk, cursorHalo };
}

/* ------------------------------------------------------------------ CSS emission */

function emitBlock(cfg, t, indent) {
  const p = ' '.repeat(indent);
  const L = [];
  const put = (k, v) => L.push(`${p}${k}: ${v};`);
  const gap = () => L.push('');

  L.push(`${p}/* neutral scale — hue ${cfg.grayHue}, chroma ${cfg.grayChroma} (tinted, not pure grey) */`);
  t.gray.steps.forEach((hex, i) => put(`--gray-${i + 1}`, hex));
  gap();
  t.hues.forEach((h, n) => {
    L.push(`${p}/* ${h.slot} — hue ${h.hue} */`);
    h.scale.steps.forEach((hex, i) => put(`--${h.slot}-${i + 1}`, hex));
    put(`--${h.slot}-on-solid`, h.scale.onSolid);
    gap();
  });

  const S = t.surfaces;
  L.push(`${p}/* ---- semantic layer: every role below names a step, never a value ---- */`);
  put('--bg', `var(--gray-${S.bg})`);
  put('--bg-subtle', `var(--gray-${S.bgSubtle})`);
  put('--surface', `var(--gray-${S.surface})`);
  put('--surface-raised', `var(--gray-${S.raised})`);
  put('--component', 'var(--gray-3)');
  put('--component-hover', 'var(--gray-4)');
  gap();
  L.push(`${p}/* The diagram's edge captions are drawn with a knockout stroke that has to MATCH`);
  L.push(`${p}   the card fill behind them. Naming that dependency stops it breaking silently`);
  L.push(`${p}   the day the card stops being --surface. */`);
  put('--knockout', `var(--gray-${S.surface})`);
  gap();
  L.push(`${p}/* borders: 6 is decorative and exempt from 1.4.11; 8 carries meaning at 3:1 */`);
  put('--border', 'var(--gray-6)');
  put('--border-strong', 'var(--gray-7)');
  put('--border-meaningful', 'var(--gray-8)');
  put('--graphic-line', 'var(--gray-8)');
  gap();
  L.push(`${p}/* text: three levels, ALL of which meet AA. The faintest is step 11 at 4.5:1 —`);
  L.push(`${p}   there is nothing below it, and reaching for one is what broke this before. */`);
  put('--text', 'var(--gray-12)');
  put('--text-muted', t.textMid);
  put('--text-faint', 'var(--gray-11)');
  gap();
  L.push(`${p}/* brand: 9 fills, 11 sets type. One token cannot do both jobs. */`);
  put('--primary', 'var(--hue1-9)');
  put('--primary-strong', 'var(--hue1-10)');
  put('--primary-text', 'var(--hue1-11)');
  put('--primary-text-strong', 'var(--hue1-12)');
  put('--primary-contrast', 'var(--hue1-on-solid)');
  put('--primary-subtle', 'var(--hue1-3)');
  put('--primary-line', 'var(--hue1-8)');
  gap();
  put('--accent', 'var(--hue2-9)');
  put('--accent-strong', 'var(--hue2-10)');
  put('--accent-text', 'var(--hue2-11)');
  put('--accent-text-strong', 'var(--hue2-12)');
  put('--accent-contrast', 'var(--hue2-on-solid)');
  put('--accent-subtle', 'var(--hue2-3)');
  put('--accent-line', 'var(--hue2-8)');
  gap();
  put('--tertiary', 'var(--hue3-9)');
  put('--tertiary-text', 'var(--hue3-11)');
  put('--tertiary-contrast', 'var(--hue3-on-solid)');
  put('--tertiary-subtle', 'var(--hue3-3)');
  put('--tertiary-line', 'var(--hue3-8)');
  gap();
  L.push(`${p}/* section washes — a surface tint per hue. Text is verified ON these too. */`);
  t.washes.forEach((w, i) => {
    put(`--wash-${i + 1}`, w.hexes[0]);
    put(`--wash-${i + 1}-deep`, w.hexes[1]);
  });
  gap();
  L.push(`${p}/* focus: must clear 3:1 against the page and against the dark code island */`);
  put('--focus-ring', t.ringPage);
  put('--focus-ring-on-code', t.ringOnCode);
  gap();
  L.push(`${p}/* the pointer: two-tone, constant across configurations. The ink is a stated`);
  L.push(`${p}   choice; the halo is the dark end of the neutral scale. On every surface at`);
  L.push(`${p}   least one of the two clears 4.5:1 — see CURSOR_INK in the generator. */`);
  put('--cursor-ink', t.cursorInk);
  put('--cursor-halo', t.cursorHalo);
  gap();
  L.push(`${p}/* status hues are constant across configurations — see STATUS in the generator */`);
  put('--warning', t.warnScale.steps[10]);
  put('--warning-solid', t.warnScale.steps[8]);
  put('--warning-subtle', t.warnScale.steps[2]);
  put('--danger', t.dangScale.steps[10]);
  put('--danger-solid', t.dangScale.steps[8]);
  put('--danger-subtle', t.dangScale.steps[2]);
  gap();
  L.push(`${p}/* code island: a dark surface in both themes, so tokens are pinned to it */`);
  put('--code-bg', t.codeBg);
  put('--code-border', t.codeBorder);
  put('--code-text', t.codeText);
  put('--code-muted', t.codeMuted);
  t.codeTokens.forEach((c) => put(`--code-${c.token}`, c.hex));

  return L.join('\n');
}

function emitCss(cfg) {
  const light = buildTheme(cfg, 'light');
  const dark = buildTheme(cfg, 'dark');
  return [
    START,
    `/* configuration: ${cfg.id} — "${cfg.name}"`,
    ` * ${cfg.character}`,
    ` * Regenerate with:  node scripts/generate-palette.mjs ${cfg.id}`,
    ` */`,
    ':root {',
    emitBlock(cfg, light, 2),
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme="light"]) {',
    emitBlock(cfg, dark, 4),
    '  }',
    '}',
    '',
    ':root[data-theme="dark"] {',
    emitBlock(cfg, dark, 2),
    '}',
    END,
  ].join('\n');
}

/* ------------------------------------------------------------------ verification */

function verify(cfg) {
  const rows = [];
  for (const mode of ['light', 'dark']) {
    const t = buildTheme(cfg, mode);
    const beds = t.surfaceHexes.concat(t.washBeds);
    const check = (label, fg, target, against) => {
      const worst = Math.min(...against.map((b) => contrast(fg, b)));
      const at = against[against.findIndex((b) => contrast(fg, b) === worst)];
      rows.push({ mode, label, fg, bed: at, ratio: +worst.toFixed(2), need: target, pass: worst >= target });
    };

    check('text (gray.12) on every surface', t.gray.steps[11], NEED.step12, beds);
    check('muted + caption (gray.11) on every surface', t.gray.steps[10], NEED.step11, beds);
    check('graphic line (gray.8) on every surface', t.gray.steps[7], NEED.step8, beds);
    t.hues.forEach((h) => {
      const own = [h.scale.steps[1], h.scale.steps[2]];
      check(`${h.slot} text (11) on surfaces + own tint`, h.scale.steps[10], NEED.step11, beds.concat(own));
      check(`${h.slot} solid (9) vs page`, h.scale.steps[8], NEED.step9, [beds[0]]);
      check(`${h.slot} text ON solid (9)`, h.scale.onSolid, NEED.onSolid, [h.scale.steps[8]]);
      check(`${h.slot} line (8) on every surface`, h.scale.steps[7], NEED.step8, beds.concat(own));
    });
    check('muted mid level (7:1 AAA) on every surface', t.textMid, 7.0, beds);
    check('warning text on surfaces', t.warnScale.steps[10], NEED.step11, beds);
    check('danger text on surfaces', t.dangScale.steps[10], NEED.step11, beds);
    check('code text on code bg', t.codeText, 13, [t.codeBg]);
    check('code muted on code bg', t.codeMuted, NEED.step11, [t.codeBg]);
    t.codeTokens.forEach((c) => check(`code ${c.token} on code bg`, c.hex, NEED.step11, [t.codeBg]));
    check('focus ring vs page', t.ringPage, 3.0, [beds[0]]);
    check('focus ring vs code island', t.ringOnCode, 3.0, [t.codeBg]);
    /* The pointer is a PAIR, so the obligation is on the pair: every surface it can
       cross must be cleared by at least one of the two tones. Checking the ink alone
       is the wrong test for a two-tone mark — it would reject a pale ink that a dark
       rim makes perfectly visible, and it would pass a mid-tone ink whose rim adds
       nothing on the code island. */
    const cursorBeds = beds.concat([t.codeBg]);
    const pairWorst = Math.min(...cursorBeds.map((b) =>
      Math.max(contrast(t.cursorInk, b), contrast(t.cursorHalo, b))));
    const pairBed = cursorBeds.find((b) =>
      Math.max(contrast(t.cursorInk, b), contrast(t.cursorHalo, b)) === pairWorst);
    rows.push({
      mode, label: 'cursor pair (ink OR halo) on every surface it crosses',
      fg: `${t.cursorInk}/${t.cursorHalo}`, bed: pairBed,
      ratio: +pairWorst.toFixed(2), need: 4.5, pass: pairWorst >= 4.5,
    });
    check('cursor ink vs its own halo', t.cursorInk, 3.0, [t.cursorHalo]);

    /* Mutual distinguishability of the syntax set — measured through BOTH dichromat
       simulations, because a syntax highlighter is the one thing on this page that cannot
       add a label or an icon: colour is genuinely its only channel. Normal-vision
       separation is not reported, since it is never the binding constraint. */
    const worstPair = { d: Infinity };
    for (const kind of ['deuteranopia', 'protanopia']) {
      const colourOnly = t.codeTokens.filter((c) => !c.styled);
      for (let i = 0; i < colourOnly.length; i++) {
        for (let j = i + 1; j < colourOnly.length; j++) {
          const a = colourOnly[i], b = colourOnly[j];
          const d = deltaE(simulate(a.hex, kind), simulate(b.hex, kind));
          if (d < worstPair.d) Object.assign(worstPair, { d, kind, a: a.token, b: b.token, ah: a.hex, bh: b.hex });
          rows.push({ mode, cvd: true, label: `syntax ${a.token}/${b.token} under ${kind}`,
            fg: a.hex, bed: b.hex, ratio: +d.toFixed(3), need: NEED.cvdSyntax, pass: d >= NEED.cvdSyntax });
        }
      }
      /* And the brand hues, at the two steps where they carry meaning. */
      for (const st of [9, 11]) {
        for (let i = 0; i < t.hues.length; i++) {
          for (let j = i + 1; j < t.hues.length; j++) {
            const a = t.hues[i], b = t.hues[j];
            const d = deltaE(simulate(a.scale.steps[st - 1], kind), simulate(b.scale.steps[st - 1], kind));
            rows.push({ mode, cvd: true, label: `${a.slot}/${b.slot} step ${st} under ${kind}`,
              fg: a.scale.steps[st - 1], bed: b.scale.steps[st - 1], ratio: +d.toFixed(3), need: NEED.cvdBrand, pass: d >= NEED.cvdBrand });
          }
        }
      }
    }
    rows.push({ mode, label: `WORST syntax pair (${worstPair.kind}: ${worstPair.a}/${worstPair.b})`,
      fg: worstPair.ah, bed: worstPair.bh, ratio: +worstPair.d.toFixed(3), need: NEED.cvdSyntax, pass: worstPair.d >= NEED.cvdSyntax });

    t.codeTokens.filter((c) => c.chroma < 0.05).forEach((c) => {
      const gap = contrast(t.codeText, t.codeBg) / contrast(c.hex, t.codeBg);
      rows.push({ mode, label: `syntax ${c.token} recedes from plain code text`, fg: c.hex, bed: t.codeText, ratio: +gap.toFixed(2), need: 1.35, pass: gap >= 1.35 });
    });
  }
  return rows;
}

/* OKLab hue angle difference, for "are these two token colours telling me apart?" */
function rgbToOklab(hex) {
  const [r, g, b] = hexToRgb(hex).map((v) => srgbToLinear(v / 255));
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return {
    L: 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    a: 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    b: 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  };
}
/* OKLab Euclidean distance — a perceptual "can I tell these apart" number. Used on
   SIMULATED colours, which is the only way to answer the question for a dichromat. */
function deltaE(h1, h2) {
  const A = rgbToOklab(h1), B = rgbToOklab(h2);
  return Math.hypot(A.L - B.L, A.a - B.a, A.b - B.b);
}

function deltaHue(h1, h2) {
  const A = rgbToOklab(h1), B = rgbToOklab(h2);
  const a1 = (Math.atan2(A.b, A.a) * 180) / Math.PI, a2 = (Math.atan2(B.b, B.a) * 180) / Math.PI;
  let d = Math.abs(a1 - a2) % 360;
  return d > 180 ? 360 - d : d;
}

/* ------------------------------------------------------------------ cli */

const [, , id, ...flags] = process.argv;

if (!id) {
  console.log('configurations:');
  Object.values(CONFIGS).forEach((c) => console.log(`  ${c.id.padEnd(24)} ${c.name} — ${c.character}`));
  process.exit(0);
}
const cfg = CONFIGS[id];
if (!cfg) { console.error(`unknown configuration "${id}". Run with no argument to list.`); process.exit(2); }

if (flags.includes('--verify')) {
  const rows = verify(cfg);
  const fails = rows.filter((r) => !r.pass);
  console.log(`\n${cfg.id} — "${cfg.name}"\n`);
  for (const mode of ['light', 'dark']) {
    console.log(`  == ${mode} ==`);
    rows.filter((r) => r.mode === mode).forEach((r) =>
      console.log(`    ${r.pass ? ' ok ' : 'FAIL'} ${String(r.ratio).padStart(7)} (need ${String(r.need).padEnd(5)}) ${r.fg} on ${r.bed}  ${r.label}`));
  }
  const worstText = rows.filter((r) => r.need === 4.5).sort((a, b) => a.ratio - b.ratio)[0];
  console.log(`\n  worst text pair: ${worstText.fg} on ${worstText.bed} = ${worstText.ratio}:1 (${worstText.label}, ${worstText.mode})`);
  console.log(`  ${fails.length} obligation(s) unmet\n`);
  process.exit(fails.length ? 1 : 0);
}

const css = emitCss(cfg);
if (flags.includes('--stdout')) { console.log(css); process.exit(0); }

const src = readFileSync(CSS, 'utf8');
const a = src.indexOf(START), b = src.indexOf(END);
if (a === -1 || b === -1) {
  console.error(`markers not found in ${CSS}.\nAdd these two lines where the palette should live:\n${START}\n${END}`);
  process.exit(2);
}
writeFileSync(CSS, src.slice(0, a) + css + src.slice(b + END.length), 'utf8');
const fails = verify(cfg).filter((r) => !r.pass);
console.log(`wrote ${cfg.id} into assets/css/styles.css — ${fails.length ? fails.length + ' UNMET obligation(s), run --verify' : 'all obligations met'}`);

/* The favicon is a data: URI, so it has no stylesheet and cannot reference a token. It is
   the single place in the project where a colour must be hand-kept in sync — so the tool
   that changes the palette reports exactly what the favicon should become. */
{
  const t = buildTheme(cfg, 'light');
  const enc = (h) => '%23' + h.slice(1);
  console.log('\nfavicon in index.html is a data: URI and cannot use tokens — sync these three:');
  console.log(`  badge fill        ${t.hues[0].scale.steps[8]}   ->  ${enc(t.hues[0].scale.steps[8])}`);
  console.log(`  document rules    ${t.gray.steps[0]}   ->  ${enc(t.gray.steps[0])}`);
  console.log(`  lit "hit" line    ${t.hues[1].scale.steps[8]}   ->  ${enc(t.hues[1].scale.steps[8])}`);
}
